- type: construction
  id: DoubleStunbaton
  graph: DoubleStunbatonGraph
  startNode: start
  targetNode: end
  RequiresEngineeringLevel: 2
  category: construction-category-weapons
  objectType: Item
